project:
  type: website
  output-dir: docs

website:
  title: "Rafael Bressan"
  favicon: img/favicon2.jpg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - text: Teaching
        menu: 
          - href: microeconomia1.qmd
            text: Microeconomia I
          - href: econometria3.qmd
            text: Econometria III
          - href: int_trade.qmd
            text: International Trade
          - href: microeconometrics1.qmd
            text: Microeconometrics I
      - about.qmd
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/rafael-bressan-5b4063b3/
      - icon: github
        href: https://github.com/rfbressan
      - icon: twitter
        href: https://twitter.com/RafaelBressan9

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true



